### ISSUE TITLE
pynguin does not generate tests for all functions in the module

### ISSUE THREAD

**Issue by adder46** [se2p/pynguin#2]
I've tried pynguin out of curiosity for my [dpaster](https://github.com/adder46/dpaster) project, and it was only able to generate test cases for one function - `get_syntax`. The other two functions in the application module were not considered. Also, IMHO, the test cases generated for the `get_syntax` function looked very machine-generated, at best.

**Comment by stephanlukasczyk** [comment]
Hi @adder46 ,
Thank you for your interest in Pynguin. Thank you also for reporting your experiences back.

I'd like to investigate a bit on this and maybe come up with a reason, why Pynguin only considered the `get_syntax` function, and whether we can fix this. It sounds like a bug, though. For this, could you please paste me the full command-line to Pynguin you were using for your experiment, such that I can debug this.

Please note that Pynguin is a research prototype still at a very early development stage, thus not production ready. Hence, we expect test cases to look very machine-generated for now. Future work might improve this, but this extension is currently not scheduled for any specific future release.

**Comment by adder46** [comment]
No problem, it seems like a fun project.

The command I used was:

```
pynguin --algorithm WSPY --project_path dpaster/ --output_path tests/ --module_name dpaster.application
```

**Comment by stephanlukasczyk** [comment]
Hi,
Sorry for the delay, I was finally able to spend some time on this and debug it.

From what I understand, `click` seems to be the “root of all evil”. Pynguin uses the [`inspect.getmembers`](https://docs.python.org/3.8/library/inspect.html#inspect.getmembers) to find all classes, methods, and functions in a module (see [`TestClusterGenerator#generate_cluster()`](https://github.com/se2p/pynguin/blob/003a58bea95bc5c2db654253469963cd51d3021a/pynguin/setup/testclustergenerator.py#L81)). Now, when loading the `dpaster` project, this method from standard API yields only one public function (i.e. a function defined in that module, its name not starting with `_`)—`get_syntax` that matches the used filter predicates [`class_in_module`](https://github.com/se2p/pynguin/blob/003a58bea95bc5c2db654253469963cd51d3021a/pynguin/utils/type_utils.py#L34) or [`function_in_module`](https://github.com/se2p/pynguin/blob/003a58bea95bc5c2db654253469963cd51d3021a/pynguin/utils/type_utils.py#L47).

The other functions from your module are not yielded as function or class type but as objects of type `Command`—which I suspect to come from the used decorator `@config.command` in their source code. While searching for this, I found similar issues (e.g. https://github.com/pdoc3/pdoc/issues/166#issuecomment-587871751) which indicate that `click`'s `@config.command` does not yield the original function properly. Inspecting the yielded `Command` object, I was not able to find a reference to the wrapped callable, i.e., the original function, but only its name as a string. Not even [`inspect.unwrap`](https://docs.python.org/3.8/library/inspect.html#inspect.unwrap) provided me this function. Here I am stuck now, not knowing how to get this wrapped callable in order to incorporate it in our test cluster, i.e., make it a candidate function for test generation.

Since I don't know a way to fix this, I'll close this issue, although feeling sad about it. Maybe, there is a solution for this in `click` that I am not aware of (I have not used that library so far); if so, please point me to it in order to allow proper fixing of this issue.
