### ISSUE TITLE
doc is dead: 500 or 522 error

### ISSUE THREAD

**Issue by Symbolk** [se2p/pynguin#24]
https://pynguin.readthedocs.io/en/latest/user/quickstart.html
Hi, one issue about the doc: when clicking the `Assertions` link, it breaks the whole doc site and return 500 error in Chrome and 522 error in Edge, could you replicate that and fix it?

**Comment by stephanlukasczyk** [comment]
Thank you for reporting this.  Unfortunately, I cannot do too much about it.  The docs are hosted by [readthedocs](https://readthedocs.org) and it seems like they have some issues with serving the content; at least I cannot view there [status page](https://status.readthedocs.com/).  At least, I can reproduce the issue here.

The only thing I can recommend to do is trying it later, please.

**Comment by Symbolk** [comment]
> Thank you for reporting this. Unfortunately, I cannot do too much about it. The docs are hosted by [readthedocs](https://readthedocs.org) and it seems like they have some issues with serving the content; at least I cannot view there [status page](https://status.readthedocs.com/). At least, I can reproduce the issue here.
> 
> The only thing I can recommend to do is trying it later, please.

Thanks. Not sure it is proper to ask here, but I have two quick questions:
1. I just found that running this tool sometimes causes my system to reboot (Centos), was this reported before? 
2. I noticed that the minimal granularity is module/file, does it support generate tests only for a class or function?

**Comment by stephanlukasczyk** [comment]
> Thanks. Not sure it is proper to ask here, but I have two quick questions:
> 
> I just found that running this tool sometimes causes my system to reboot (Centos), was this reported before?

This might be possible.  The reason is explained in the large warning box on top of the [quickstart](https://pynguin.readthedocs.io/en/latest/user/quickstart.html).  TL;DR: Pynguin executes the module for which it generates tests.  This can cause harm to your system.  That's why we require a user to set the `PYNGUIN_DANGER_AWARE` environment variable: to show that the user is aware of the risk of execution arbitrary code.

> I noticed that the minimal granularity is module/file, does it support generate tests only for a class or function?

Currently not.

**Comment by Symbolk** [comment]
> 

Alright, thanks!
