### ISSUE TITLE
Trouble with testing a repository

### ISSUE THREAD

**Issue by freddiewanah** [se2p/pynguin#49]
Hi, I've read your paper and saw you have tried to test pynguin in repositories such as sanic.

However, when I configured a local environment for sanic, and try to run the command such as
`PYNGUIN_DANGER_AWARE=1 pynguin --algorithm DYNAMOSA --project_path . --output_path ./test_pynguin --module_name sanic.http --assertion_generation SIMPLE`

I got this error message.

```
ERROR    SUT contains nothing we can test.
```

Issue https://github.com/se2p/pynguin/issues/10 looks similar, but I think I tried the exact suggestion given from one of the contributors. 

What should be the correct command to use pynguin for such cases?

**Comment by stephanlukasczyk** [comment]
Thank you for your interest in Pynguin. I assume the issue is due to the fact that you've tried to execute it on the package `sanic.http`, which will implicitly attempt to generate tests for the `__init__.py` file.  I am not sure about the exact reason without further investigation, but since that file is only containing imports from other modules, it might cause the struggle.

Running Pynguin on a module, such as `sanic.http.stream` seems to work without errors—although I need to admit that the result is not very helpful...
