### ISSUE TITLE
How can I only generate testcases for the functions in the input source file?

### ISSUE THREAD

**Issue by Andres981231** [se2p/pynguin#62]
I want to ignore the functions in the dependent modules included in the souce file. Is there any configuration to help me only generate testcases for the functions in the input source file? Thanks.

**Comment by Andres981231** [comment]
Can adding modules to the MODULE_BLACKLIST works? And Why in the comment says that MODULE_BLACKLIST should keep sorted？

**Comment by BergLucas** [comment]
Hi @Andres981231, there is no configuration available at the moment.

With the current implementation, it should work to add the dependent modules in the blacklist but if one of the classes of the module inherits from a class of a dependant module, the superclass will become available.

I don't think there's any explanation from the implementation about sorting blacklisted modules, but it makes it easier to find out whether a module is in the list or not, so it's more a convention to make the code more readable.

I hope this has answered your questions, have a nice day!

**Comment by Andres981231** [comment]
Thanks a lot. I will try to implement by myself.

**Comment by stephanlukasczyk** [comment]
Thanks to @BergLucas for the excellent answer.  Adding modules to the blacklist should do the trick.  If you want, @Andres981231 , I could also add a CLI option that would allow you to add modules to that list, without manipulating the Python code of Pynguin, which would make things probably easier from a user's perspective.  Should I do that?

Regarding the sorting of the list: there is no particular reason to it except that it makes it easier to find out whether a module already has been blacklisted (since the list is already quite long).  I'll add a clarifying comment to the code.

**Comment by Andres981231** [comment]
An CLI option will actually helps a lot. Thanks!
