### ISSUE TITLE
Issue with test case generation -- Number of classes

### ISSUE THREAD

**Issue by AFaverooo** [se2p/pynguin#77]
Hi, I am trying out pynguin for the first time and I am not sure I am following the steps to set up test generation correctly since I keep running into some issues.

I am using python 3.10.11, I set up everything in a python virtualenv. below is a screenshot of the example.py file and the test_example.py output and the output when running the specified commands in bash terminal.
![example-test-example](https://github.com/user-attachments/assets/af0fd8a5-81a2-4691-8cdb-3e17f83d11d4)

The two main issues I am encountering is that the types suggested by the triangle function do not seem to be prioritised. Some tests use Bools, strings and objects while the documentation shows the outputted tests should have mainly ints either positive or negative. Not sure why I am having these issues. 

I think the issue is to do with the second screenshot.
![image](https://github.com/user-attachments/assets/3014628c-f6c7-48a6-9c32-35aedfe0593a)
 In green I highlighted the Classes: output and it says there are 11 when it should be 0. There are no imports of any kind, my thought was because it is somehow reading the .venv file since thats the only thing

To be completely honest I am relatively new to automatic test case generation so I am not sure how to debug these issues.

Any help is appreciated.

Thank you

**Comment by stephanlukasczyk** [comment]
Thank you for your interest in Pynguin.  The number of classes (11) is due to the fact that Pynguin includes several builtins of the Python language, e.g., `int`, into this analysis.  They are available to every module without imports, see https://docs.python.org/3.10/library/functions.html

Pynguin attempts to generate other types, too, as you've encountered. While these types (and their respective initialisations) do not match the type signature, they also contribute to coverage.  To be honest, I agree that this behaviour is somehow counter-intuitive and that there should probably be an optimisation step before export that could removes such test cases under certain conditions.

**Comment by AFaverooo** [comment]
Thank you Stephan for your prompt response, what you have said makes sense, based on what I had read around pynguin maximising code coverage was something I was expecting, however since the docs showed completely different types being used for the generated tests I was worried I had somehow messed something up during the setting up steps. 

Thank you for clarifying.
